
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import CounterContractArtifactJson from './counter_contract-Counter.json' with { type: 'json' };
export const CounterContractArtifact = loadContractArtifact(CounterContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Counter;
 */
export class CounterContract extends ContractBase {

  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, CounterContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, CounterContract.artifact, wallet) as Promise<CounterContract>;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, owner: AztecAddressLike) {
    return new DeployMethod<CounterContract>(PublicKeys.default(), wallet, CounterContractArtifact, CounterContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, owner: AztecAddressLike) {
    return new DeployMethod<CounterContract>(publicKeys, wallet, CounterContractArtifact, CounterContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CounterContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CounterContract['methods'][M]>
  ) {
    return new DeployMethod<CounterContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CounterContractArtifact,
      CounterContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CounterContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(CounterContractArtifactJson as NoirCompiledContract);
  }


  public static get storage(): ContractStorageLayout<'owner' | 'follower_notes'> {
    return {
      owner: {
        slot: new Fr(1n),
      },
      follower_notes: {
        slot: new Fr(3n),
      }
    } as ContractStorageLayout<'owner' | 'follower_notes'>;
  }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** add_follower_note(circuitInputs: struct, zk_id: field, nostr_pubkey: struct, owner: struct) */
    add_follower_note: ((circuitInputs: { vkey: FieldLike[], vkey_hash: FieldLike, proof: FieldLike[], public_inputs: FieldLike[] }, zk_id: FieldLike, nostr_pubkey: AztecAddressLike, owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** add_follower_note_nocheck(nostr_pubkey: struct, owner: struct) */
    add_follower_note_nocheck: ((nostr_pubkey: AztecAddressLike, owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(owner: struct) */
    constructor: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_nostr_pubkeys(owner: struct) */
    get_nostr_pubkeys: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** view_follower_notes(owner: struct) */
    view_follower_notes: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


}
